#!/bin/bash

cc="g++ -g -Isrc -Ilibraries"
cflags="-lm -lglfw3 -lGL -lX11 -ldl -lpthread -lrt"

if [[ $# -ne 1 ]] ; then
    echo "give good args"
    exit 0
else
    name=$1
    make build/rays.o
    $cc "scenes/$name.cpp" build/rays.o -o "build/executables/render_$name" $cflags
    "./build/executables/render_$name"
fi

